version: "3.8"

services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      - TZ=Asia/Seoul
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.0
    container_name: redis-db
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
